# Generated by Django 5.0.6 on 2024-06-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_chatuser_chat_remove_chatuser_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chats',
            field=models.ManyToManyField(related_name='chat_messages', to='chat.chat'),
        ),
    ]
