# Generated by Django 5.0.6 on 2024-06-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_chats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='message',
            name='chats',
        ),
    ]
