# Generated by Django 5.0.6 on 2024-06-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_userprofile_chats_alter_chat_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='current_chat',
            new_name='chat',
        ),
    ]
