# Generated by Django 5.0.6 on 2024-06-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_rename_current_chat_message_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
