# Generated by Django 5.0.6 on 2024-06-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_chat_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('PR', 'private'), ('OP', 'open')], default='PR', max_length=10),
        ),
    ]
